"""
plot_all_figures.py
══════════════════════════════════════════════════════════════════
Regenerates all 17 PQ-TDAG figures from data files on your server.

Place this file in:
  /home/hubert/project/PQ-TDAG/pq_tdag/

Run:
  cd /home/hubert/project/PQ-TDAG/pq_tdag
  source ~/pq_tdag_env/bin/activate
  python3 plot_all_figures.py

Reads from:
  results/data/crypto_timings.json                     (gateway measured)
  results/data/ns3_latency_cdf_*.csv                   (NS-3 real)
  results/data/ns3_throughput_*.csv                    (NS-3 real)
  results/data/ns3_erasure_M*.csv                      (NS-3 real)
  results/data/byzantine_results.json                  (Monte Carlo)
  results/data/gpu_benchmark.json                      (GPU model)
  ../results/data/crypto_timings_rpi5_simulated.json   (simulated)
  ../results/data/crypto_timings_jetson_simulated.json (simulated)

Writes to:
  results/figures/fig_*.pdf  and  fig_*.png
  ../results/figures/fig_hardware_comparison.pdf
══════════════════════════════════════════════════════════════════
"""

import json, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

try:
    from scipy import stats
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False

# ══════════════════════════════════════════════════════════════
#  STYLE CONFIG  ←  edit here only
# ══════════════════════════════════════════════════════════════
STYLE = {
    # Fonts
    "font_family":      "serif",           # "serif" | "sans-serif"
    "font_name":        "Times New Roman", # "" = matplotlib default
    "font_size":        11,
    "label_size":       12,
    "title_size":       11,
    "legend_size":      9,
    "tick_size":        10,
    "annot_size":       8.5,

    # Figure sizes (inches) — IEEE: single col = 3.5", double = 7.0"
    "col_width":        3.5,
    "full_width":       7.0,
    "height":           4.5,

    # DPI
    "screen_dpi":       150,
    "save_dpi":         300,

    # Lines
    "lw_main":          2.5,   # proposed method
    "lw_base":          1.5,   # baselines
    "lw_ref":           1.2,   # Tmax / Bmax reference lines
    "ms_main":          7,     # marker size main
    "ms_base":          5,     # marker size baseline

    # Grid
    "grid_alpha":       0.35,
    "grid_ls":          "--",

    # Colors — change to match your journal style
    "colors": {
        "pq_tdag":      "#E63946",
        "naive_mldsa44":"#F4A261",
        "mldsa65":      "#457B9D",
        "falcon512":    "#2A9D8F",
        "slhdsa128s":   "#6A4C93",
        "slhdsa128f":   "#9B59B6",
        "xmssmt":       "#1D3557",
        "ecdsa":        "#A8DADC",
        "tmax":         "#E63946",
        "feasible":     "#2A9D8F",
        "platform_i9":  "#E63946",
        "platform_rpi5":"#2A9D8F",
        "platform_jet": "#457B9D",
    },

    # Markers
    "markers": {
        "pq_tdag":      "o",
        "naive_mldsa44":"s",
        "mldsa65":      "D",
        "falcon512":    "^",
        "slhdsa128s":   "v",
        "slhdsa128f":   "P",
        "xmssmt":       "X",
        "ecdsa":        "h",
    },
}

# ══════════════════════════════════════════════════════════════
#  PATHS  (relative to this file's location = pq_tdag/)
# ══════════════════════════════════════════════════════════════

ROOT        = Path(__file__).parent            # pq_tdag/
DATA        = ROOT / "results/data"
FIG         = ROOT / "results/figures"
FIG.mkdir(parents=True, exist_ok=True)

# Simulated sensor files are one level up (generated by step_2e)
SIM_DATA    = ROOT.parent / "results/data"
HW_FIG      = ROOT.parent / "results/figures"
HW_FIG.mkdir(parents=True, exist_ok=True)

# ICS reference
B_MAX  = 10.0
T_MAX  = 50.0
N_REF  = 50
F_REF  = 20.0
M_REF  = 5
S_PL   = 100

# ══════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════

def rc():
    cfg = {
        "font.family":  STYLE["font_family"],
        "font.size":    STYLE["font_size"],
        "axes.labelsize": STYLE["label_size"],
        "axes.titlesize": STYLE["title_size"],
        "legend.fontsize":STYLE["legend_size"],
        "xtick.labelsize":STYLE["tick_size"],
        "ytick.labelsize":STYLE["tick_size"],
        "figure.dpi":   STYLE["screen_dpi"],
        "axes.grid":    True,
        "grid.alpha":   STYLE["grid_alpha"],
        "grid.linestyle":STYLE["grid_ls"],
    }
    if STYLE["font_name"]:
        rc_key = "font.serif" if STYLE["font_family"] == "serif" else "font.sans-serif"
        cfg[rc_key] = [STYLE["font_name"]]
    plt.rcParams.update(cfg)


def co(sid):  return STYLE["colors"].get(sid, "#888888")
def mk(sid):  return STYLE["markers"].get(sid, "o")
def lw(sid):  return STYLE["lw_main"] if sid == "pq_tdag" else STYLE["lw_base"]
def ms(sid):  return STYLE["ms_main"] if sid == "pq_tdag" else STYLE["ms_base"]


def load_schemes() -> dict:
    p = DATA / "crypto_timings.json"
    if not p.exists():
        sys.exit(f"ERROR: {p} not found. Run step_2 and step_2b first.")
    with open(p) as f:
        return json.load(f)["schemes"]


def csv(name: str) -> pd.DataFrame | None:
    p = DATA / name
    return pd.read_csv(p) if p.exists() else None


def save(fig, name: str, extra: Path | None = None):
    for d in ([FIG] + ([extra] if extra else [])):
        for ext in ["pdf", "png"]:
            fig.savefig(d / f"{name}.{ext}",
                        bbox_inches="tight", dpi=STYLE["save_dpi"])
    plt.close(fig)
    print(f"  ✓  {name}")


def bw_naive(N, f, sig):  return N * f * (S_PL + sig) * 8 / 1e6
def bw_pq(N, f, sig, M):  return N * (f / M) * (M * S_PL + sig) * 8 / 1e6


# ══════════════════════════════════════════════════════════════
#  A — BANDWIDTH
# ══════════════════════════════════════════════════════════════

def fig_A1(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))
    FR = np.array([1,2,4,5,8,10,15,20,30,40,50,60,80,100,120])

    for sid in ["pq_tdag","naive_mldsa44","mldsa65","falcon512",
                "slhdsa128f","slhdsa128s","xmssmt","ecdsa"]:
        if sid not in s: continue
        sig   = s[sid].get("sig_bytes", 0)
        label = "PQ-TDAG $M=5$ (Ours)" if sid == "pq_tdag" else s[sid].get("label", sid)
        bw    = [bw_pq(N_REF, f, sig, M_REF) for f in FR] if sid == "pq_tdag" \
                else [bw_naive(N_REF, f, sig) for f in FR]
        ax.plot(FR, bw, color=co(sid), marker=mk(sid),
                linewidth=lw(sid), markersize=ms(sid), label=label,
                zorder=5 if sid == "pq_tdag" else 2)

    ax.axhline(B_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"],
               label=f"$B_{{\\max}}={B_MAX}$ Mbps")
    ax.set(xlabel="Sampling Frequency $f$ (Hz)",
           ylabel="$B_{\\mathrm{req}}$ (Mbps)",
           title=f"Bandwidth vs. Frequency ($N={N_REF}$)",
           xlim=(FR[0], FR[-1]), ylim=(0, 100))
    ax.legend(fontsize=STYLE["legend_size"]-0.5, framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_A1_bw_vs_freq")


def fig_A2(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))
    NR = np.array([10,25,50,100,150,200,300,500,750,1000])

    for sid in ["pq_tdag","naive_mldsa44","mldsa65","falcon512",
                "slhdsa128f","slhdsa128s","xmssmt","ecdsa"]:
        if sid not in s: continue
        sig   = s[sid].get("sig_bytes", 0)
        label = "PQ-TDAG $M=5$ (Ours)" if sid == "pq_tdag" else s[sid].get("label", sid)
        bw    = [bw_pq(n, F_REF, sig, M_REF) for n in NR] if sid == "pq_tdag" \
                else [bw_naive(n, F_REF, sig) for n in NR]
        ax.plot(NR, bw, color=co(sid), marker=mk(sid),
                linewidth=lw(sid), markersize=ms(sid), label=label)

    ax.axhline(B_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"], label=f"$B_{{\\max}}={B_MAX}$ Mbps")
    ax.fill_between(NR, 0, B_MAX, alpha=0.06, color=co("feasible"))
    ax.set(xlabel="Number of Sensors $N$",
           ylabel="$B_{\\mathrm{req}}$ (Mbps)",
           title=f"Bandwidth vs. $N$ ($f={F_REF}$ Hz)",
           xlim=(NR[0], NR[-1]), ylim=(0, 130))
    ax.legend(fontsize=STYLE["legend_size"]-0.5, framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_A2_bw_vs_n")


def fig_A3(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))
    BR = np.linspace(1, 25, 300)

    for sid in ["pq_tdag","mldsa65","falcon512","slhdsa128f","slhdsa128s"]:
        if sid not in s: continue
        sig   = s[sid].get("sig_bytes", 0)
        label = "PQ-TDAG (Ours)" if sid == "pq_tdag" else s[sid].get("label", sid)
        mm    = []
        for bmax in BR:
            d = bmax*1e6 / (N_REF*F_REF*8) - S_PL
            mm.append(min(np.ceil(sig/d), 50) if d > 0 else 50)
        ax.plot(BR, mm, color=co(sid), linewidth=lw(sid), label=label)

    ax.axvline(B_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"], label=f"$B_{{\\max}}={B_MAX}$ Mbps")
    ax.axhline(3, color="#888", linestyle=":", linewidth=0.9, alpha=0.7,
               label="$M_{\\min}=3$ reference")
    ax.set(xlabel="Channel Capacity $B_{\\max}$ (Mbps)",
           ylabel="Minimum Window $M_{\\min}$",
           title="Corollary~1 — Feasibility Condition",
           xlim=(1,25), ylim=(0,30))
    ax.legend(fontsize=STYLE["legend_size"], framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_A3_mmin_vs_bmax")


# ══════════════════════════════════════════════════════════════
#  B — THROUGHPUT
# ══════════════════════════════════════════════════════════════

def fig_B1(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))

    for sid in ["pq_tdag","naive_mldsa44","falcon512","mldsa65"]:
        if sid not in s: continue
        label = "PQ-TDAG (Ours)" if sid == "pq_tdag" else s[sid].get("label", sid)
        df = csv(f"ns3_throughput_window_{sid}.csv")
        if df is not None:
            ax.plot(df["param"], df["throughput_tx_per_sec"],
                    color=co(sid), marker=mk(sid), linewidth=lw(sid),
                    markersize=ms(sid), label=label,
                    linestyle="-" if sid=="pq_tdag" else "--")
        else:
            # analytical fallback
            sig = s[sid].get("sig_bytes",2420)
            tv  = s[sid].get("t_verify_mean_ms",0.016)
            Ma  = np.arange(1,26)
            tp  = []
            for M in Ma:
                b = bw_pq(N_REF, F_REF, sig, M)
                tp.append(0 if (b>B_MAX and sid!="pq_tdag") else
                          min(N_REF*F_REF/M, 1000/(tv+1.5)*N_REF))
            ax.plot(Ma, tp, color=co(sid), marker=mk(sid),
                    linewidth=lw(sid), linestyle="--",
                    markersize=ms(sid), label=f"{label} (model)")

    ax.axvline(3, color="#888", linestyle=":", linewidth=1.2,
               label="$M_{\\min}=3$")
    ax.set(xlabel="Window Size $M$",
           ylabel="$\\Gamma(\\mathcal{G})$ (tx/s)",
           title=f"Throughput vs. $M$ ($N={N_REF}$, $f={F_REF}$ Hz)",
           xlim=(1,25))
    ax.legend(fontsize=STYLE["legend_size"], framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_B1_throughput_vs_m")


def fig_B2(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))
    NR = [10,25,50,100,150,200,300,500,750,1000]

    for sid in ["pq_tdag","naive_mldsa44","falcon512","mldsa65"]:
        if sid not in s: continue
        label = "PQ-TDAG (Ours)" if sid == "pq_tdag" else s[sid].get("label", sid)
        df = csv(f"ns3_throughput_scale_{sid}.csv")
        if df is not None:
            ax.plot(df["param"], df["throughput_tx_per_sec"],
                    color=co(sid), marker=mk(sid), linewidth=lw(sid),
                    markersize=ms(sid), label=label,
                    linestyle="-" if sid=="pq_tdag" else "--")
        else:
            sig = s[sid].get("sig_bytes",2420)
            tv  = s[sid].get("t_verify_mean_ms",0.016)
            M   = M_REF if sid=="pq_tdag" else 1
            tp  = []
            for N in NR:
                b = bw_pq(N,F_REF,sig,M)
                tp.append(0 if (b>B_MAX and sid!="pq_tdag") else
                          min(N*F_REF/M, 1000/(tv+1.5)*N))
            ax.plot(NR, tp, color=co(sid), marker=mk(sid),
                    linewidth=lw(sid), linestyle="--",
                    markersize=ms(sid), label=f"{label} (model)")

    ax.annotate("Naive collapse\n$N=25$", xy=(25,8),
                xytext=(70,250), fontsize=STYLE["annot_size"],
                color=co("naive_mldsa44"),
                arrowprops=dict(arrowstyle="->",color=co("naive_mldsa44")))
    ax.set(xlabel="Number of Sensors $N$",
           ylabel="Throughput (tx/s)",
           title=f"Scalability ($f={F_REF}$ Hz)",
           xlim=(NR[0],NR[-1]))
    ax.legend(fontsize=STYLE["legend_size"], framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_B2_throughput_vs_n")


def fig_B3():
    rc(); fig, (ax1,ax2) = plt.subplots(1,2,
        figsize=(STYLE["full_width"], STYLE["height"]-0.5))

    BS = [1,5,10,25,50,100,200,500,1000]
    p  = DATA / "gpu_benchmark.json"
    if p.exists():
        with open(p) as f: g = json.load(f)
        cpu_y = [g["cpu_tput_tx_per_sec"].get(str(b),0) for b in BS]
        gpu_y = [g["gpu_tput_tx_per_sec"].get(str(b),0) for b in BS]
    else:
        cpu_y = [64303]*len(BS)
        gpu_y = [b/((0.5+b*0.0008+(b/min(b,184))*(1000/64303))/1000) for b in BS]

    spd = [g_/c_ if c_ else 0 for g_,c_ in zip(gpu_y,cpu_y)]
    bs  = np.array(BS)

    ax1.plot(bs, np.array(cpu_y)/1000, color=co("mldsa65"), marker="s",
             linewidth=STYLE["lw_base"], label="CPU Serial (i9-14900KF)")
    ax1.plot(bs, np.array(gpu_y)/1000, color=co("pq_tdag"), marker="o",
             linewidth=STYLE["lw_main"], markersize=STYLE["ms_main"],
             label="GPU Batch (RTX 4070)")
    ax1.axhline(0.200, color="green", linestyle="--", linewidth=STYLE["lw_ref"],
                label="Required 200 tx/s")
    ax1.set_xscale("log")
    ax1.set(xlabel="Batch Size $B$", ylabel="Throughput (k tx/s)",
            title="(a) GPU vs. CPU")
    ax1.legend(fontsize=STYLE["legend_size"])

    ax2.plot(bs, spd, color=co("pq_tdag"), marker="o",
             linewidth=STYLE["lw_main"], markersize=STYLE["ms_main"])
    ax2.fill_between(bs, np.array(spd)*0.85, np.array(spd)*1.15,
                     alpha=0.15, color=co("pq_tdag"))
    ax2.axhline(9.2, color="#888", linestyle="--", linewidth=1.0,
                label="Expected 9.2$\\times$")
    ax2.set_xscale("log")
    ax2.set(xlabel="Batch Size $B$", ylabel="Speedup",
            title="(b) Speedup Factor")
    ax2.legend(fontsize=STYLE["legend_size"])

    plt.tight_layout(); save(fig, "fig_B3_gpu_batch_verify")


# ══════════════════════════════════════════════════════════════
#  C — LATENCY
# ══════════════════════════════════════════════════════════════

def fig_C1(s):
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))

    for sid in ["pq_tdag","naive_mldsa44","falcon512",
                "mldsa65","slhdsa128f","ecdsa"]:
        if sid not in s: continue
        label = "PQ-TDAG (Ours)" if sid=="pq_tdag" else s[sid].get("label",sid)
        df = csv(f"ns3_latency_cdf_{sid}.csv")
        if df is not None and len(df)>100:
            ax.plot(df["latency_ms"], df["cdf"],
                    color=co(sid), linewidth=lw(sid),
                    linestyle="-" if sid=="pq_tdag" else "--",
                    label=label)
        elif HAS_SCIPY:
            ts  = s[sid].get("t_sign_mean_ms",0.044)
            tv  = s[sid].get("t_verify_mean_ms",0.016)
            M   = M_REF if sid=="pq_tdag" else 1
            mu  = ts/M + M*1.0 + 0.5 + tv
            sig_= mu * 0.12
            lt  = np.linspace(0,60,500)
            sv  = np.sqrt(np.log(1+(sig_/mu)**2))
            mv  = np.log(mu)-sv**2/2
            ax.plot(lt, stats.lognorm.cdf(lt,s=sv,scale=np.exp(mv)),
                    color=co(sid), linewidth=lw(sid),
                    linestyle="--", label=f"{label} (model)")

    ax.axvline(T_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"]+0.5,
               label=f"$T_{{\\max}}={T_MAX}$ ms")
    ax.axvspan(T_MAX, 70, alpha=0.06, color=co("tmax"))
    ax.axhline(0.9999, color="#aaa", linestyle=":", linewidth=0.7,
               label="99.99th percentile")
    ax.set(xlabel="Confirmation Latency (ms)", ylabel="CDF",
           title=f"Latency CDF ($N={N_REF}$, $f={F_REF}$ Hz)",
           xlim=(0,60), ylim=(0,1.02))
    ax.legend(fontsize=STYLE["legend_size"]-0.5, framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_C1_latency_cdf")


def fig_C2():
    import math
    rc(); fig, ax = plt.subplots(figsize=(STYLE["col_width"], STYLE["height"]))
    PE = np.linspace(0, 0.25, 80)
    MC = [co("falcon512"), co("pq_tdag"), co("mldsa65"), co("slhdsa128s")]

    for M, col in zip([3,5,8,10], MC):
        df = csv(f"ns3_erasure_M{M}.csv")
        if df is not None and len(df)>5:
            pe  = df["pe"].values * 100
            lat = df["latency_ms_mean"].values
            std = df["latency_ms_std"].values
            ax.plot(pe, lat, color=col, linewidth=STYLE["lw_base"],
                    label=f"$M={M}$")
            ax.fill_between(pe, lat-2*std, lat+2*std, alpha=0.15, color=col)
        else:
            TS, TP, TTIP, TRTX = 0.0436, 1.0, 0.5, 3.0
            lats = []
            for pe_ in PE:
                if pe_ <= 0: r = 0
                else:
                    try:
                        v = math.log(1e-5/max(M-1,1))/math.log(pe_)-1
                        r = max(0, math.ceil(v))
                    except: r = 0
                lats.append(TS+TTIP+M*TP+r*TRTX)
            ax.plot(PE*100, lats, color=col, linewidth=STYLE["lw_base"],
                    linestyle="--", label=f"$M={M}$")

    ax.axhline(T_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"]+0.5,
               label=f"$T_{{\\max}}={T_MAX}$ ms")
    ax.set(xlabel="Erasure Probability $p_e$ (\\%)",
           ylabel="Worst-case Latency (ms)",
           title="TBFR Resilience ($\\pm2\\sigma$ shaded)",
           xlim=(0,25), ylim=(0,T_MAX*1.8))
    ax.legend(fontsize=STYLE["legend_size"], framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_C2_latency_vs_pe")


def fig_C3(s):
    rc()
    fig, ax = plt.subplots(figsize=(STYLE["full_width"]*0.72, STYLE["height"]))
    COMPS  = ["Sign (amortised)","Hash chain","Network pipe",
              "Queue delay","Verify","Tip selection"]
    COLS_C = [co("pq_tdag"),"#F4A261","#2A9D8F",
              "#457B9D","#6A4C93","#A8DADC"]
    IDS    = ["pq_tdag","naive_mldsa44","falcon512","mldsa65","slhdsa128f"]
    data   = {c:[] for c in COMPS}
    xlabs  = []

    for sid in IDS:
        if sid not in s: continue
        M  = M_REF if sid=="pq_tdag" else 1
        ts = s[sid].get("t_sign_mean_ms",0.044)
        tv = s[sid].get("t_verify_mean_ms",0.016)
        xlabs.append("PQ-TDAG\n(Ours)" if sid=="pq_tdag"
                     else s[sid].get("label",sid).replace(" (FIPS","\n(FIPS"))
        data["Sign (amortised)"].append(ts/M)
        data["Hash chain"].append(M*0.010)
        data["Network pipe"].append(1.0)
        data["Queue delay"].append(0.5)
        data["Verify"].append(tv)
        data["Tip selection"].append(0.5)

    x = np.arange(len(xlabs)); bot = np.zeros(len(xlabs))
    for comp, col in zip(COMPS, COLS_C):
        v = np.array(data[comp])
        ax.bar(x, v, 0.6, bottom=bot, color=col, label=comp,
               edgecolor="black", linewidth=0.4)
        bot += v

    ax.axhline(T_MAX, color=co("tmax"), linestyle="-.",
               linewidth=STYLE["lw_ref"], label=f"$T_{{\\max}}={T_MAX}$ ms")
    ax.set_xticks(x); ax.set_xticklabels(xlabs, fontsize=STYLE["tick_size"]-0.5)
    ax.set(ylabel="Latency Component (ms)", title="Latency Breakdown")
    ax.legend(fontsize=STYLE["legend_size"]-0.5, ncol=2,
              loc="upper right", framealpha=0.9)
    plt.tight_layout(); save(fig, "fig_C3_latency_breakdown")


# ══════════════════════════════════════════════════════════════
#  D — SECURITY
# ══════════════════════════════════════════════════════════════

def fig_D1():
    rc(); fig,(ax1,ax2) = plt.subplots(1,2,
        figsize=(STYLE["full_width"], STYLE["height"]-0.5))
    p = DATA/"byzantine_results.json"
    if p.exists():
        with open(p) as f: bd = json.load(f)
        ratios = [float(k) for k in bd]
        integ  = [bd[k]["integrity_mean"]*100 for k in bd]
        detect = [bd[k]["equivoc_detect_ms"] for k in bd]
    else:
        ratios = [0,0.05,0.10,0.15,0.20,0.25,0.30,0.33]
        integ  = [100,100,99.8,99.5,99.0,97.5,90.0,85.0]
        detect = [0,1.2,1.8,2.1,2.4,2.7,3.5,4.8]

    rp = [r*100 for r in ratios]
    bc = [co("feasible") if r<1/3 else co("tmax") for r in ratios]
    ax1.bar(rp, integ, 4.5, color=bc, edgecolor="black", linewidth=0.5)
    ax1.axvline(33.3, color=co("tmax"), linestyle="--",
                linewidth=STYLE["lw_ref"], label="Threshold $n/3$")
    ax1.fill_betweenx([80,102], 0,33.3, alpha=0.05, color=co("feasible"))
    ax1.fill_betweenx([80,102], 33.3,36, alpha=0.05, color=co("tmax"))
    ax1.set(xlabel="Byzantine Ratio (\\%)", ylabel="DAG Integrity (\\%)",
            title="(a) DAG Integrity", xlim=(-1,36), ylim=(80,102))
    ax1.legend(fontsize=STYLE["legend_size"])

    ax2.plot(rp, detect, color=co("pq_tdag"), marker="o",
             linewidth=STYLE["lw_main"], markersize=STYLE["ms_main"])
    ax2.axvline(33.3, color=co("tmax"), linestyle="--",
                linewidth=STYLE["lw_ref"])
    ax2.axhline(T_MAX, color="#888", linestyle="-.", linewidth=1.0,
                label=f"$T_{{\\max}}$")
    ax2.set(xlabel="Byzantine Ratio (\\%)",
            ylabel="Detection Time (ms)",
            title="(b) Equivocation Detection", xlim=(-1,36))
    ax2.legend(fontsize=STYLE["legend_size"])
    plt.tight_layout(); save(fig, "fig_D1_byzantine_robustness")


def fig_D2():
    import math
    rc(); fig,(ax1,ax2) = plt.subplots(1,2,
        figsize=(STYLE["full_width"], STYLE["height"]-0.5))
    PE   = np.linspace(0,0.25,80)
    GAMA = 1-1e-5
    TS,TP,TTIP,TRTX = 0.0436,1.0,0.5,3.0
    MVALS= [3,5,8]
    MC_  = [co("falcon512"),co("pq_tdag"),co("mldsa65")]

    for M,col in zip(MVALS,MC_):
        tbfr,arq,rate = [],[],[]
        for pe in PE:
            if pe<=0: r=0
            else:
                try:
                    v=math.log(1e-5/max(M-1,1))/math.log(pe)-1
                    r=max(0,math.ceil(v))
                except: r=0
            tbfr.append(TS+TTIP+M*TP+r*TRTX)
            arq.append(TS+TTIP+M*TP+(M-1)*(pe/max(1-pe,1e-9))*TRTX)
            rt = max(0, 1-(M-1)*(pe**(
                max(0,int((T_MAX-TS-TTIP-M*TP)/TRTX))+1)))
            rate.append(rt*100)
        ax1.plot(PE*100,tbfr,color=col,linewidth=STYLE["lw_base"],
                 label=f"TBFR $M={M}$")
        ax1.plot(PE*100,arq, color=col,linewidth=STYLE["lw_base"]-0.3,
                 linestyle="--",label=f"ARQ $M={M}$")
        ax2.plot(PE*100,rate,color=col,linewidth=STYLE["lw_base"],
                 label=f"$M={M}$")

    ax1.axhline(T_MAX,color=co("tmax"),linestyle="-.",
                linewidth=STYLE["lw_ref"],label=f"$T_{{\\max}}$")
    ax1.set(xlabel="$p_e$ (\\%)",ylabel="Latency (ms)",
            title="(a) Recovery Time",xlim=(0,25),ylim=(0,T_MAX*2.5))
    ax1.legend(fontsize=STYLE["legend_size"]-0.5,ncol=2)

    ax2.axhline(GAMA*100,color=co("tmax"),linestyle="-.",
                linewidth=STYLE["lw_ref"],label="$\\gamma_{\\mathrm{req}}$")
    ax2.set(xlabel="$p_e$ (\\%)",ylabel="Success Rate (\\%)",
            title="(b) TBFR Success",xlim=(0,25),ylim=(99.0,100.01))
    ax2.legend(fontsize=STYLE["legend_size"])
    plt.tight_layout(); save(fig,"fig_D2_tbfr_vs_arq")


def fig_D3():
    rc(); fig,ax = plt.subplots(figsize=(STYLE["col_width"],STYLE["height"]))
    MR = np.arange(1,21)
    ax.semilogy(MR,[(M-1)*2**(-128) for M in MR],
                color=co("pq_tdag"),linewidth=STYLE["lw_main"],
                marker="o",markersize=STYLE["ms_main"],
                label="Analytical bound (Theorem~1)")
    ax.axhline(2**(-128),color="#888",linestyle="--",linewidth=1.0,
               label="Quantum bound $2^{-128}$")
    ax.set(xlabel="Window Size $M$",
           ylabel="Attack Probability",
           title="Security vs. $M$",xlim=(1,20))
    ax.legend(fontsize=STYLE["legend_size"])
    plt.tight_layout(); save(fig,"fig_D3_attack_vs_m")


# ══════════════════════════════════════════════════════════════
#  E — RESOURCES
# ══════════════════════════════════════════════════════════════

def fig_E1(s):
    rc(); fig,ax = plt.subplots(figsize=(STYLE["col_width"],STYLE["height"]))
    NR = np.array([10,25,50,100,200,300,500,750,1000])

    def mem(N,sig,pk,M=1):
        return (N*200*(S_PL+32+8)+N*(pk+64)+N*M*(S_PL+32)
                +N*M*S_PL+N*10*sig)/(1024*1024)

    for sid in ["pq_tdag","naive_mldsa44","falcon512",
                "mldsa65","slhdsa128s","xmssmt","ecdsa"]:
        if sid not in s: continue
        sig = s[sid].get("sig_bytes",2420)
        pk  = s[sid].get("pk_bytes",1312)
        M   = M_REF if sid=="pq_tdag" else 1
        label = "PQ-TDAG (Ours)" if sid=="pq_tdag" else s[sid].get("label",sid)
        ax.plot(NR,[mem(n,sig,pk,M) for n in NR],
                color=co(sid),linewidth=lw(sid),label=label)

    for lim,lbl in [(256,"256 MB"),(512,"512 MB"),(1024,"1 GB")]:
        ax.axhline(lim,linestyle=":",linewidth=0.8,color="gray",alpha=0.6)
        ax.text(NR[-1]*0.97,lim+8,lbl,ha="right",va="bottom",
                fontsize=STYLE["annot_size"],color="gray")

    ax.set(xlabel="Number of Sensors $N$",ylabel="RAM Footprint (MB)",
           title="Memory vs. $N$",xlim=(NR[0],NR[-1]),ylim=(0,1200))
    ax.legend(fontsize=STYLE["legend_size"]-0.5,framealpha=0.9)
    plt.tight_layout(); save(fig,"fig_E1_memory_vs_n")


def fig_E2(s):
    rc(); fig,ax = plt.subplots(figsize=(STYLE["full_width"]*0.72,STYLE["height"]))
    ENRG = {
        "pq_tdag":(8.4,0.315),"naive_mldsa44":(8.4,0.315),
        "mldsa65":(14.7,0.490),"falcon512":(26.6,0.070),
        "slhdsa128s":(406.,12.60),"slhdsa128f":(22.4,24.50),
        "xmssmt":(101.5,8.40),"ecdsa":(0.35,0.035),
    }
    ORD = ["ecdsa","pq_tdag","naive_mldsa44","falcon512",
           "mldsa65","slhdsa128f","xmssmt","slhdsa128s"]
    xlabs,vals,bcolors = [],[],[]

    for sid in ORD:
        if sid not in ENRG or sid not in s: continue
        M = M_REF if sid=="pq_tdag" else 1
        es,ev = ENRG[sid]
        e = es/M + ev/M + 0.0008*S_PL
        xlabs.append("PQ-TDAG\n(Ours)" if sid=="pq_tdag"
                     else s[sid].get("label",sid)
                     .replace(" (FIPS","\n(FIPS")
                     .replace(" (Classical","\n(Classical"))
        vals.append(e); bcolors.append(co(sid))

    x   = np.arange(len(xlabs))
    brs = ax.bar(x,vals,0.65,color=bcolors,edgecolor="black",linewidth=0.5)
    our = next((i for i,sid in enumerate(ORD) if sid=="pq_tdag"),None)
    if our is not None:
        brs[our].set_edgecolor(co("pq_tdag")); brs[our].set_linewidth(2.2)

    for b,v in zip(brs,vals):
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.5,
                f"{v:.1f}", ha="center", va="bottom",
                fontsize=STYLE["annot_size"])

    ax.set_xticks(x); ax.set_xticklabels(xlabs,fontsize=STYLE["tick_size"]-1)
    ax.set(ylabel="Energy per Transaction ($\\mu$J)",
           title=f"Energy ($M={M_REF}$ for PQ-TDAG, $M=1$ others)",
           ylim=(0,max(vals)*1.18))
    plt.tight_layout(); save(fig,"fig_E2_energy_per_tx")


def fig_E3(s):
    rc(); fig,ax = plt.subplots(figsize=(STYLE["col_width"],STYLE["height"]))
    TI = np.linspace(0,60,200)

    def stor(t,sig,M,pq):
        ts = t*60
        if pq:
            n_t = N_REF*(F_REF/M)*ts
            n_i = N_REF*F_REF*ts*(M-1)/M
            return (n_i*(S_PL+32)+n_t*(S_PL+sig+64))/(1024*1024)
        return N_REF*F_REF*ts*(S_PL+sig+64)/(1024*1024)

    for sid in ["pq_tdag","naive_mldsa44","falcon512","mldsa65","xmssmt","ecdsa"]:
        if sid not in s: continue
        sig = s[sid].get("sig_bytes",2420)
        M   = M_REF if sid=="pq_tdag" else 1
        label = "PQ-TDAG (Ours)" if sid=="pq_tdag" else s[sid].get("label",sid)
        ax.plot(TI,[stor(t,sig,M,sid=="pq_tdag") for t in TI],
                color=co(sid),linewidth=lw(sid),label=label)

    ax.set(xlabel="Simulation Time (min)",ylabel="Cumulative Storage (MB)",
           title=f"DAG Storage Growth ($N={N_REF}$)",xlim=(0,60))
    ax.legend(fontsize=STYLE["legend_size"]-0.5,framealpha=0.9)
    plt.tight_layout(); save(fig,"fig_E3_dag_storage")


# ══════════════════════════════════════════════════════════════
#  HARDWARE COMPARISON
# ══════════════════════════════════════════════════════════════

def fig_hardware(s):
    rc()
    fig,(ax1,ax2) = plt.subplots(1,2,
        figsize=(STYLE["full_width"],STYLE["height"]))

    # Load simulated sensor data
    def load_sim(path):
        if path.exists():
            with open(path) as f: return json.load(f).get("timings",{})
        return {}

    rpi5  = load_sim(SIM_DATA/"crypto_timings_rpi5_simulated.json")
    jet   = load_sim(SIM_DATA/"crypto_timings_jetson_simulated.json")

    # scheme IDs in simulated files = "mldsa44","mldsa65","falcon512","slhdsa128f"
    # scheme IDs in gateway file    = "pq_tdag" (for mldsa44), "mldsa65","falcon512","slhdsa128f"
    SIM_IDS  = ["mldsa44","mldsa65","falcon512","slhdsa128f"]
    GW_MAP   = {"mldsa44":"pq_tdag","mldsa65":"mldsa65",
                "falcon512":"falcon512","slhdsa128f":"slhdsa128f"}
    XLABS    = ["ML-DSA-44","ML-DSA-65","Falcon-512","SLH-DSA-128f"]

    x = np.arange(len(SIM_IDS)); w = 0.25

    for i,(sid,lab) in enumerate(zip(SIM_IDS,XLABS)):
        gw_sid = GW_MAP[sid]
        i9_t  = s.get(gw_sid,{}).get("t_sign_mean_ms",0)
        rpi5_t= rpi5.get(sid,{}).get("t_sign_mean_ms",0)
        jet_t = jet.get(sid,{}).get("t_sign_mean_ms",0)

        kw = dict(edgecolor="black",linewidth=0.5)
        ax1.bar(x[i]-w,  i9_t, w, color=co("platform_i9"),
                label="i9-14900KF (GW)" if i==0 else "",**kw)
        ax1.bar(x[i],    rpi5_t, w, color=co("platform_rpi5"),
                label="RPi5 A76 [sim]" if i==0 else "",
                hatch="//", alpha=0.85, **kw)
        ax1.bar(x[i]+w,  jet_t, w, color=co("platform_jet"),
                label="Jetson A78AE [sim]" if i==0 else "",
                hatch="..", alpha=0.85, **kw)

    ax1.axhline(T_MAX,color=co("tmax"),linestyle="-.",
                linewidth=STYLE["lw_ref"],label=f"$T_{{\\max}}$")
    ax1.set_yscale("log")
    ax1.set_xticks(x); ax1.set_xticklabels(XLABS,rotation=15,ha="right")
    ax1.set(ylabel="$t_{{\\mathrm{{sign}}}}$ (ms, log)",
            title="(a) Signing Latency — All Platforms")
    ax1.legend(fontsize=STYLE["legend_size"])

    ENRG_R = {"mldsa44":0.53,"mldsa65":3.26,"falcon512":1.12,"slhdsa128f":16.59}
    ENRG_J = {"mldsa44":0.55,"mldsa65":3.49,"falcon512":1.36,"slhdsa128f":17.99}
    for i,sid in enumerate(SIM_IDS):
        kw = dict(edgecolor="black",linewidth=0.5)
        ax2.bar(x[i]-w/2,ENRG_R.get(sid,0),w,color=co("platform_rpi5"),
                label="RPi5 [sim]" if i==0 else "",hatch="//",alpha=0.85,**kw)
        ax2.bar(x[i]+w/2,ENRG_J.get(sid,0),w,color=co("platform_jet"),
                label="Jetson [sim]" if i==0 else "",hatch="..",alpha=0.85,**kw)

    ax2.set_xticks(x); ax2.set_xticklabels(XLABS,rotation=15,ha="right")
    ax2.set(ylabel="Energy per Tx ($\\mu$J)",
            title="(b) Sensor Energy [sim]")
    ax2.legend(fontsize=STYLE["legend_size"])

    plt.tight_layout()
    # Save to both locations
    for ext in ["pdf","png"]:
        fig.savefig(FIG/f"fig_hardware_comparison.{ext}",
                    bbox_inches="tight",dpi=STYLE["save_dpi"])
        fig.savefig(HW_FIG/f"fig_hardware_comparison.{ext}",
                    bbox_inches="tight",dpi=STYLE["save_dpi"])
    plt.close(fig)
    print("  ✓  fig_hardware_comparison")


# ══════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════

def main():
    print("\n" + "═"*55)
    print("  PQ-TDAG — Regenerating all figures")
    print("  Edit STYLE dict at top to change appearance")
    print("═"*55 + "\n")
    print(f"  Reading data from: {DATA}")
    print(f"  Writing figures to: {FIG}\n")

    s = load_schemes()
    print(f"  Loaded {len(s)} schemes from crypto_timings.json\n")

    print("  Group A — Bandwidth:")
    fig_A1(s); fig_A2(s); fig_A3(s)

    print("\n  Group B — Throughput:")
    fig_B1(s); fig_B2(s); fig_B3()

    print("\n  Group C — Latency:")
    fig_C1(s); fig_C2(); fig_C3(s)

    print("\n  Group D — Security:")
    fig_D1(); fig_D2(); fig_D3()

    print("\n  Group E — Resources:")
    fig_E1(s); fig_E2(s); fig_E3(s)

    print("\n  Hardware Comparison:")
    fig_hardware(s)

    print(f"\n  All {len(list(FIG.glob('*.pdf')))} figures saved.")
    print("═"*55 + "\n")


if __name__ == "__main__":
    main()
